# Generated by Django 4.2.3 on 2024-03-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocalMarket', '0016_alter_customer_address_alter_customer_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_zip_code',
        ),
    ]
