# Generated by Django 4.2.3 on 2024-03-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalMarket', '0018_alter_order_shop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='shoppics/vendorShop.jpeg', null=True, upload_to='shoppics/'),
        ),
    ]
